### PR TITLE
Added 404 page with links to other pages

### PR DESCRIPTION
**Pull request by abelhbeyene**
@faithwins instead of redirecting users I have added links to other pages.
image

### CODE REVIEW

**Comment by faithwins** [comment]
@abelhbeyene That is good. I like it. Only concern I have is it might have unintended consequence in terms of user experience. Say, someone clicked on one of those links. He would see the detailed page. The detailed page has a back button that takes you to Home. But, the user would think back button would take them back to the 404 page. 
So, to make the user experience right, we can do these:
1. You add one more button in that list for Home page.
2. Rename "Back" button to "Home" - will ask the team's opinion since this will be a deviation from the design too.

thoughts?

**Comment by abelhbeyene** [comment]
@faithwins I agree. Sounds like the simplest option is option 2. Happy to go with that..

**Comment by faithwins** [comment]
Ok. I will ask the team's opinion on it. And, I wasn't presenting the two options as one or the other. Was kinda thinking both. User can go straight to home page if they choose to or through the other pages.

**Comment by faithwins** [comment]
@abelhbeyene looks like it is a go for renaming "Back" to "Home"

**Comment by abelhbeyene** [comment]
@faithwins - PR updated

**Pull request merged**
